# Generated by Django 3.2.5 on 2021-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('emp', 'Employee'), ('cus', 'Customer'), ('adm', 'Admin')], max_length=100),
        ),
    ]
