# Generated by Django 3.2.5 on 2021-07-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='request_date',
        ),
    ]
