# Generated by Django 3.2.5 on 2021-07-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orders',
            new_name='types',
        ),
    ]
